title: "VLA-RFT"
description: "World Model-Based RL Fine-Tuning for Robot Manipulation"
theme: jekyll-theme-primer

# GitHub Pages 설정 (이 구역을 아래처럼 수정해 주세요)
url: "https://ml1team.github.io"
baseurl: "/VLA-introduction"

# 마크다운 설정
markdown: kramdown
kramdown:
  input: GFM
# 플러그인
plugins:
  - jekyll-seo-tag
# 네비게이션 제거 (단일 페이지)
header_pages: []
